DROP TABLE http_request;
CREATE TABLE http_request (
guid char(36),
acceptcharset string,
acceptencoding string,
acceptlanguage string,
acceptlan string,
accept string,
ac string,
cachecontrol string,
connection string,
contenttype string,
cookie string,
dnt string,
host string,
iclouddsid string,
ifmodifiedsince string,
ifnonematch string,
keepalive string,
origin string,
purpose string,
pragma string,
referer string,
resourcefreshness string,
useragent string,
verbose string,
xapplestorefront string,
xclientdata string,
xdsid string,
xigcapabilities string,
xnewrelicid string,
xflashversion string,
xplaybacksessionid string,
xrequestedwith string
);
